version: "3.8"

services:

    mysql:
      image: mysql:8.0
      container_name: mysql
      working_dir: /app
      volumes:
        - ./docker/mysql/data:/var/lib/mysql:rw
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      ports:
        - "31000:3306"

    webserver:
      image: nginx:latest
      container_name: webserver
      working_dir: /app
      depends_on:
        - mysql
        - php
      volumes:
          - ./app:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
       - "8080:80"
      hostname: 127.0.0.1:8080
      links:
        - mysql
        - php

    php:
      image: lukashron/php80rc2fpm:latest
      container_name: php
      working_dir: /app
      volumes:
        - ./app:/app
        - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini:ro